services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - .:/app
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge